WITH RankEcoli AS (
    SELECT ID, SIZE_OF_COLONY, 
           RANK() OVER (ORDER BY SIZE_OF_COLONY) AS SIZE_RANK,
           COUNT(*) OVER() AS TOTAL_COUNT
    FROM ECOLI_DATA
)
SELECT ID, 
       CASE 
           WHEN SIZE_RANK <= TOTAL_COUNT/4 THEN 'LOW'
           WHEN SIZE_RANK <= 2*TOTAL_COUNT/4 THEN 'MEDIUM'
           WHEN SIZE_RANK <= 3*TOTAL_COUNT/4 THEN 'HIGH'
           ELSE 'CRITICAL'
       END AS COLONY_NAME
FROM RankEcoli
ORDER BY ID;
